Fixed noSuchMethodError
For some reason removing the super. call fixed an issue that caused a
noSuchMethodError.
I presume this a some kind of kotlin issue as this happened after we
updated the kotlin version.